/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import Vroom_UAS.User;
import javax.swing.*;
import java.awt.event.*;

/**
 *
 * @author arg
 */
public class FormMenu extends javax.swing.JFrame {
    /**
     * Creates new form Menu
     */
    private User currentUser;
    
    public FormMenu() {
        initComponents();
    }

    public FormMenu(User user) {
        initComponents();

        
        // Tambahkan aksi tombol di sini
        btnlogout.addActionListener((ActionEvent evt) -> {
            dispose(); // Tutup Menu
            new FormHome_login().setVisible(true); // Kembali ke login
        });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnlogout = new javax.swing.JButton();
        btnTambahmobil = new javax.swing.JButton();
        btnBalikin = new javax.swing.JButton();
        btnPinjammobil = new javax.swing.JButton();
        btnTambahuser = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(186, 152, 145));
        jPanel1.setPreferredSize(new java.awt.Dimension(781, 401));

        btnlogout.setBackground(new java.awt.Color(23, 42, 76));
        btnlogout.setFont(new java.awt.Font("Calisto MT", 1, 18)); // NOI18N
        btnlogout.setForeground(new java.awt.Color(131, 147, 187));
        btnlogout.setText("Keluar");
        btnlogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlogoutActionPerformed(evt);
            }
        });

        btnTambahmobil.setBackground(new java.awt.Color(23, 42, 76));
        btnTambahmobil.setFont(new java.awt.Font("Calisto MT", 1, 18)); // NOI18N
        btnTambahmobil.setForeground(new java.awt.Color(131, 147, 187));
        btnTambahmobil.setText("Tambah Mobil");
        btnTambahmobil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahmobilActionPerformed(evt);
            }
        });

        btnBalikin.setBackground(new java.awt.Color(23, 42, 76));
        btnBalikin.setFont(new java.awt.Font("Calisto MT", 1, 18)); // NOI18N
        btnBalikin.setForeground(new java.awt.Color(131, 147, 187));
        btnBalikin.setText("Kembalikan Mobil");
        btnBalikin.setActionCommand("");
        btnBalikin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBalikinActionPerformed(evt);
            }
        });

        btnPinjammobil.setBackground(new java.awt.Color(23, 42, 76));
        btnPinjammobil.setFont(new java.awt.Font("Calisto MT", 1, 18)); // NOI18N
        btnPinjammobil.setForeground(new java.awt.Color(131, 147, 187));
        btnPinjammobil.setText("Sewa Mobil");
        btnPinjammobil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPinjammobilActionPerformed(evt);
            }
        });

        btnTambahuser.setBackground(new java.awt.Color(23, 42, 76));
        btnTambahuser.setFont(new java.awt.Font("Calisto MT", 1, 18)); // NOI18N
        btnTambahuser.setForeground(new java.awt.Color(131, 147, 187));
        btnTambahuser.setText("Tambah User");
        btnTambahuser.setActionCommand("");
        btnTambahuser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahuserActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Mobil2.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnPinjammobil, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnTambahmobil, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnlogout, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnTambahuser, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnBalikin, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 125, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(btnlogout, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnTambahmobil, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnPinjammobil, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnBalikin, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnTambahuser, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 433, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTambahuserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahuserActionPerformed
        // TODO add your handling code here:
        TambahUser tambahUser = new TambahUser(); // Buka form TambahUser
        tambahUser.setVisible(true);
        dispose(); // Tutup MenuStaff

    }//GEN-LAST:event_btnTambahuserActionPerformed

    private void btnBalikinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBalikinActionPerformed
        // TODO add your handling code here:
        form_pengembalian formkembali = new form_pengembalian();
        formkembali.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnBalikinActionPerformed

    private void btnPinjammobilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPinjammobilActionPerformed
        // TODO add your handling code here:
        FormPeminjaman formpeminjaman = new FormPeminjaman();
        formpeminjaman.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnPinjammobilActionPerformed

    private void btnTambahmobilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahmobilActionPerformed
        // TODO add your handling code here:
        TambahMobil tambahMobil = new TambahMobil(); // Buka form TambahMobil
        tambahMobil.setVisible(true);
        dispose(); // Tutup MenuStaff
    }//GEN-LAST:event_btnTambahmobilActionPerformed

    private void btnlogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlogoutActionPerformed
        FormHome_login formlogin = new FormHome_login();
        formlogin.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnlogoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
       java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                User dummyUser = new User("id", "Tester", "tester", "123", "Admin");
                new FormMenu(dummyUser).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBalikin;
    private javax.swing.JButton btnPinjammobil;
    private javax.swing.JButton btnTambahmobil;
    private javax.swing.JButton btnTambahuser;
    private javax.swing.JButton btnlogout;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
