
import Vroom_UAS.Pengembalian;
import java.util.ArrayList;
import javax.swing.JComboBox;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author rhevaalfareraa
 */
public class form_pengembalian extends javax.swing.JFrame {
    public ArrayList<Pengembalian> dataList;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(form_pengembalian.class.getName());

    public form_pengembalian() {
        initComponents();
        dataList = new ArrayList<>();
    
        // Isi combobox
        cbMobil.removeAllItems();
        cbMobil.addItem("B 1234 CD");
        cbMobil.addItem("D 5678 EF");
        cbMobil.addItem("F 9999 GH");
        cbMobil.addItem("E 1122 IJ");
        cbMobil.addItem("G 3344 KL");
        cbMobil.addItem("H 5566 MN");
        cbMobil.addItem("L 7788 OP");
        cbMobil.addItem("Z 9900 QR");

        // Contoh isi dataList
        dataList.add(new Pengembalian("Rheva", "123", "Jakarta", "08123", "rheva@gmail.com",
                                      "B 1234 CD", "10-06-2025", "12-06-2025", 2, 250000));
        dataList.add(new Pengembalian("Adit", "456", "Bandung", "08234", "adit@gmail.com",
                                      "D 5678 EF", "11-06-2025", "13-06-2025", 2, 300000));
        dataList.add(new Pengembalian("Pijah", "789", "Surabaya", "08345", "nina@gmail.com",
                                      "F 9999 GH", "09-06-2025", "11-06-2025", 2, 270000));
        dataList.add(new Pengembalian("Bila", "101", "Medan", "08456", "bila@gmail.com",
                                      "E 1122 IJ", "08-06-2025", "10-06-2025", 2, 240000));
        dataList.add(new Pengembalian("Rara", "202", "Yogyakarta", "08567", "rara@gmail.com",
                                      "G 3344 KL", "07-06-2025", "09-06-2025", 2, 320000));
        dataList.add(new Pengembalian("Palen", "303", "Semarang", "08678", "palen@gmail.com",
                                      "H 5566 MN", "06-06-2025", "08-06-2025", 2, 280000));
        dataList.add(new Pengembalian("Chiko", "404", "Bali", "08789", "chiko@gmail.com",
                                      "L 7788 OP", "05-06-2025", "07-06-2025", 2, 290000));
        dataList.add(new Pengembalian("Jusi", "505", "Makassar", "08890", "jusi@gmail.com",
                                      "Z 9900 QR", "04-06-2025", "06-06-2025", 2, 310000));
        tampilkanTabel();
    }
    
    private void tampilkanTabel() {
    // Bikin model dengan kolom dan cell non-editable
    DefaultTableModel model = new DefaultTableModel(
        new Object[] { "No Polisi", "Nama Peminjam", "Harga", "Tanggal Peminjaman", 
                       "Tanggal Pengembalian", "Lama Peminjaman", "Total Harga" }, 
        0 
    ) {
        @Override
        public boolean isCellEditable(int row, int column) {
            return false; // Semua cell tidak bisa diedit
        }
    };

    // Tambahkan data ke model
    for (Pengembalian p : dataList) {
        model.addRow(new Object[] {
            p.getNoPolisi(),
            p.nama,
            p.getHargaPerHari(),
            p.tglPinjam,
            p.tglKembali,
            p.getLamaPinjam(),
            p.getTotal()
        });
    }

    // Set model ke table
    tblMobil.setModel(model);

    // Atur lebar kolom
    tblMobil.setAutoResizeMode(JTable.AUTO_RESIZE_OFF); // Supaya lebar kolom sesuai preferredWidth
    tblMobil.getColumnModel().getColumn(0).setPreferredWidth(100); // No Polisi
    tblMobil.getColumnModel().getColumn(1).setPreferredWidth(120); // Nama Peminjam
    tblMobil.getColumnModel().getColumn(2).setPreferredWidth(80);  // Harga
    tblMobil.getColumnModel().getColumn(3).setPreferredWidth(120); // Tanggal Peminjaman
    tblMobil.getColumnModel().getColumn(4).setPreferredWidth(135); // Tanggal Pengembalian
    tblMobil.getColumnModel().getColumn(5).setPreferredWidth(115); // Lama Peminjaman
    tblMobil.getColumnModel().getColumn(6).setPreferredWidth(150); // Total Harga

    // Atur tinggi row
    tblMobil.setRowHeight(25);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnKembalikan = new javax.swing.JButton();
        lblPengembalian = new javax.swing.JLabel();
        lblDurasi = new javax.swing.JLabel();
        lblNama = new javax.swing.JLabel();
        lblHarga = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        noPolisi = new javax.swing.JLabel();
        namaPeminjam1 = new javax.swing.JLabel();
        totalHarga3 = new javax.swing.JLabel();
        cbMobil = new javax.swing.JComboBox<>();
        tglPeminjaman = new javax.swing.JLabel();
        tglPengembalian = new javax.swing.JLabel();
        lamaPeminjaman = new javax.swing.JLabel();
        lblPeminjaman = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMobil = new javax.swing.JTable();
        btnKembali = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(186, 152, 145));

        btnKembalikan.setBackground(new java.awt.Color(23, 42, 76));
        btnKembalikan.setFont(new java.awt.Font("Calisto MT", 1, 14)); // NOI18N
        btnKembalikan.setForeground(new java.awt.Color(131, 147, 187));
        btnKembalikan.setText("Mengembalikan Mobil");
        btnKembalikan.setToolTipText("");
        btnKembalikan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKembalikanActionPerformed(evt);
            }
        });

        lblPengembalian.setFont(new java.awt.Font("Hiragino Mincho ProN", 0, 13)); // NOI18N
        lblPengembalian.setForeground(new java.awt.Color(23, 42, 76));
        lblPengembalian.setText("lblPengembalian");

        lblDurasi.setFont(new java.awt.Font("Hiragino Mincho ProN", 0, 13)); // NOI18N
        lblDurasi.setForeground(new java.awt.Color(23, 42, 76));
        lblDurasi.setText("lblDurasi");

        lblNama.setFont(new java.awt.Font("Hiragino Mincho ProN", 0, 13)); // NOI18N
        lblNama.setForeground(new java.awt.Color(23, 42, 76));
        lblNama.setText("lblNama");

        lblHarga.setFont(new java.awt.Font("Hiragino Mincho ProN", 0, 13)); // NOI18N
        lblHarga.setForeground(new java.awt.Color(23, 42, 76));
        lblHarga.setText("lblHarga");

        jLabel4.setFont(new java.awt.Font("Calisto MT", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(23, 42, 76));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Form Pengembalian Mobil");

        noPolisi.setFont(new java.awt.Font("Hiragino Mincho ProN", 1, 14)); // NOI18N
        noPolisi.setForeground(new java.awt.Color(23, 42, 76));
        noPolisi.setText("No_Polisi : *");

        namaPeminjam1.setFont(new java.awt.Font("Hiragino Mincho ProN", 1, 14)); // NOI18N
        namaPeminjam1.setForeground(new java.awt.Color(23, 42, 76));
        namaPeminjam1.setText("Nama_Peminjam :");

        totalHarga3.setFont(new java.awt.Font("Hiragino Mincho ProN", 1, 14)); // NOI18N
        totalHarga3.setForeground(new java.awt.Color(23, 42, 76));
        totalHarga3.setText("Total_Harga :");

        cbMobil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbMobilActionPerformed(evt);
            }
        });

        tglPeminjaman.setFont(new java.awt.Font("Hiragino Mincho ProN", 1, 14)); // NOI18N
        tglPeminjaman.setForeground(new java.awt.Color(23, 42, 76));
        tglPeminjaman.setText("Tanggal_Peminjaman :");

        tglPengembalian.setFont(new java.awt.Font("Hiragino Mincho ProN", 1, 14)); // NOI18N
        tglPengembalian.setForeground(new java.awt.Color(23, 42, 76));
        tglPengembalian.setText("Tanggal_Pengembalian :");

        lamaPeminjaman.setFont(new java.awt.Font("Hiragino Mincho ProN", 1, 14)); // NOI18N
        lamaPeminjaman.setForeground(new java.awt.Color(23, 42, 76));
        lamaPeminjaman.setText("Lama Peminjaman :");

        lblPeminjaman.setFont(new java.awt.Font("Hiragino Mincho ProN", 0, 13)); // NOI18N
        lblPeminjaman.setForeground(new java.awt.Color(23, 42, 76));
        lblPeminjaman.setText("lblPeminjaman");

        tblMobil.setFont(new java.awt.Font("Hiragino Mincho ProN", 1, 14)); // NOI18N
        tblMobil.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "No Polisi", "Nama Peminjam", "Harga", "Tanggal Peminjaman", "Tanggal Pengembalian", "Lama Peminjaman", "Total Harga"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Double.class, java.lang.Object.class, java.lang.Object.class, java.lang.String.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblMobil);

        btnKembali.setBackground(new java.awt.Color(23, 42, 76));
        btnKembali.setFont(new java.awt.Font("Calisto MT", 1, 14)); // NOI18N
        btnKembali.setForeground(new java.awt.Color(131, 147, 187));
        btnKembali.setText("Kembali ke Menu");
        btnKembali.setToolTipText("");
        btnKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKembaliActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(52, 52, 52)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(noPolisi)
                                    .addComponent(namaPeminjam1)
                                    .addComponent(totalHarga3))
                                .addGap(78, 78, 78)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblHarga)
                                    .addComponent(cbMobil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblNama))
                                .addGap(124, 124, 124)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tglPeminjaman)
                                    .addComponent(tglPengembalian)
                                    .addComponent(lamaPeminjaman))
                                .addGap(55, 55, 55))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 483, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(172, 172, 172)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDurasi)
                            .addComponent(lblPengembalian)
                            .addComponent(lblPeminjaman)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 837, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(27, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnKembali)
                .addGap(18, 18, 18)
                .addComponent(btnKembalikan)
                .addGap(86, 86, 86))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel4)
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(noPolisi)
                    .addComponent(cbMobil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tglPeminjaman)
                    .addComponent(lblPeminjaman))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(namaPeminjam1)
                    .addComponent(tglPengembalian)
                    .addComponent(lblPengembalian)
                    .addComponent(lblNama))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(totalHarga3)
                    .addComponent(lamaPeminjaman)
                    .addComponent(lblDurasi)
                    .addComponent(lblHarga))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnKembalikan, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnKembali, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbMobilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbMobilActionPerformed
        // TODO add your handling code here:
        String noPol = (String) cbMobil.getSelectedItem();
        for (Pengembalian p : dataList) {
        if (p.getNoPolisi().equals(noPol)) {
            lblNama.setText(p.nama);
            lblPeminjaman.setText(p.tglPinjam);
            lblPengembalian.setText(p.tglKembali);
            lblDurasi.setText(String.valueOf(p.getLamaPinjam()));
            lblHarga.setText(String.valueOf(p.getTotal()));
        }
    }
    }//GEN-LAST:event_cbMobilActionPerformed

    private void btnKembalikanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembalikanActionPerformed
            // TODO add your handling code here:
        String noPol = (String) cbMobil.getSelectedItem();
    DefaultTableModel model = (DefaultTableModel) tblMobil.getModel();

    // Cari baris dengan no polisi yg sesuai dan hapus
    for (int i = 0; i < model.getRowCount(); i++) {
        if (model.getValueAt(i, 0).equals(noPol)) {
            model.removeRow(i);
            break; // keluar setelah hapus
        }
    }

    // Hapus dari dataList juga kalau mau bersih
    dataList.removeIf(p -> p.getNoPolisi().equals(noPol));

    // Clear label
    lblNama.setText("-");
    lblPeminjaman.setText("-");
    lblPengembalian.setText("-");
    lblDurasi.setText("-");
    lblHarga.setText("-");

    // Show notif
    javax.swing.JOptionPane.showMessageDialog(this, "Mobil berhasil dikembalikan!");
    }//GEN-LAST:event_btnKembalikanActionPerformed

    private void btnKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembaliActionPerformed
        // TODO add your handling code here:
        FormMenu form_menu = new FormMenu();
        form_menu.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnKembaliActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new form_pengembalian().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKembali;
    private javax.swing.JButton btnKembalikan;
    private javax.swing.JComboBox<String> cbMobil;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lamaPeminjaman;
    private javax.swing.JLabel lblDurasi;
    private javax.swing.JLabel lblHarga;
    private javax.swing.JLabel lblNama;
    private javax.swing.JLabel lblPeminjaman;
    private javax.swing.JLabel lblPengembalian;
    private javax.swing.JLabel namaPeminjam1;
    private javax.swing.JLabel noPolisi;
    private javax.swing.JTable tblMobil;
    private javax.swing.JLabel tglPeminjaman;
    private javax.swing.JLabel tglPengembalian;
    private javax.swing.JLabel totalHarga3;
    // End of variables declaration//GEN-END:variables

}

